# Logistic Regression

## Imports

In [7]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

## Data

An experiment was conducted on 5000 participants to study the effects of age and physical health on hearing loss, specifically the ability to hear high pitched tones. This data displays the result of the study in which participants were evaluated and scored for physical ability and then had to take an audio test (pass/no pass) which evaluated their ability to hear high frequencies. The age of the user was also noted. Is it possible to build a model that would predict someone's liklihood to hear the high frequency sound based solely on their features (age and physical score)?

* Features

    * age - Age of participant in years
    * physical_score - Score achieved during physical exam

* Label/Target

    * test_result - 0 if no pass, 1 if test passed

In [9]:
df = pd.read_csv('hearing_test.csv')

In [10]:
df.head()

    age  physical_score  test_result
0  33.0            40.7            1
1  50.0            37.2            1
2  52.0            24.7            0
3  56.0            31.0            0
4  35.0            42.9            1

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             5000 non-null   float64
 1   physical_score  5000 non-null   float64
 2   test_result     5000 non-null   int64
dtypes: float64(2), int64(1)
memory usage: 117.3 KB

In [12]:
df.describe().transpose()

                 count      mean        std   min   25%   50%   75%   max
age             5000.0  51.60900  11.287001  18.0  43.0  51.0  60.0  90.0
physical_score  5000.0  32.76026   8.169802  -0.0  26.7  35.3  38.9  50.0
test_result     5000.0   0.60000   0.489947   0.0   0.0   1.0   1.0   1.0

### Train | Test Split and Scaling

In [14]:
X = df.drop('test_result',axis=1)
y = df['test_result']

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=101)

In [23]:
scaler = StandardScaler()

In [25]:
scaled_X_train = scaler.fit_transform(X_train)
scaled_X_test = scaler.transform(X_test)

## Logistic Regression Model

In [30]:
from sklearn.linear_model import LogisticRegression

In [31]:
log_model = LogisticRegression()

In [33]:
log_model.fit(scaled_X_train,y_train)

LogisticRegression()

### Model Performance on Classification Tasks

In [37]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,plot_confusion_matrix

ImportError: cannot import name 'plot_confusion_matrix' from 'sklearn.metrics' (C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\__init__.py)

In [56]:
y_pred = log_model.predict(scaled_X_test)

In [58]:
accuracy_score(y_test,y_pred)

0.93

In [60]:
confusion_matrix(y_test,y_pred)

array([[172,  21],
       [ 14, 293]], dtype=int64)

In [ ]:
plot_confusion_matrix(log_model,scaled_X_test,y_test)

In [43]:
# Scaled so highest value=1
plot_confusion_matrix(log_model,scaled_X_test,y_test,normalize='true')

NameError: name 'plot_confusion_matrix' is not defined

In [45]:
print(classification_report(y_test,y_pred))

NameError: name 'y_pred' is not defined

## ROC and AUC

In [48]:
from sklearn.metrics import plot_roc_curve

ImportError: cannot import name 'plot_roc_curve' from 'sklearn.metrics' (C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\__init__.py)

In [50]:
plot_roc_curve(log_model,scaled_X_test,y_test)

NameError: name 'plot_roc_curve' is not defined

------
------